version: 2
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0d:1f:fa:cb:73:9d:f3:91:11:1c:37:ea:6b:10:a5:33"
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t ramyx86/veinte-coindor:$CIRCLE_SHA1 .
      - run: docker push ramyx86/veinte-coindor:$CIRCLE_SHA1
      - run: ssh -o StrictHostKeyChecking=no ramirom@35.192.146.6 "/bin/bash /home/ramirom/autodeploy/deploy.sh $CIRCLE_SHA1"    